[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200

lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature
    adafruit/RTClib
    adafruit/Adafruit BusIO
